name: Loan System API
on:
  repository_dispatch:
    types: [loan-api-request]

jobs:
  process-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Process API Request
        id: process
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Create processor script
          cat > process.js << 'EOF'
          const fs = require('fs');
          const path = require('path');
          
          // Read event data
          const eventPath = process.env.GITHUB_EVENT_PATH;
          const eventData = JSON.parse(fs.readFileSync(eventPath, 'utf8'));
          const payload = eventData.client_payload || {};
          
          const { action, type, data, id } = payload;
          
          console.log('Processing:', action, 'for', type);
          
          // Ensure data directory exists
          const dataDir = path.join(process.cwd(), 'data');
          if (!fs.existsSync(dataDir)) {
            fs.mkdirSync(dataDir, { recursive: true });
          }
          
          const filePath = path.join(dataDir, `${type}.json`);
          
          // Read existing data or create empty array
          let fileData = [];
          if (fs.existsSync(filePath)) {
            try {
              const content = fs.readFileSync(filePath, 'utf8');
              fileData = JSON.parse(content || '[]');
            } catch (e) {
              fileData = [];
            }
          }
          
          let result = { success: true };
          
          if (action === 'get') {
            result.data = fileData;
          } else if (action === 'save') {
            const timestamp = new Date().toISOString();
            
            if (id) {
              // Update existing
              const index = fileData.findIndex(item => item.id === id);
              if (index !== -1) {
                fileData[index] = { ...fileData[index], ...data, updatedAt: timestamp };
              } else {
                fileData.push({ id, ...data, createdAt: timestamp });
              }
            } else {
              // Add new
              const newId = `${type.slice(0,3).toUpperCase()}-${Date.now()}`;
              fileData.push({
                id: newId,
                ...data,
                createdAt: timestamp,
                currency: 'TZS'
              });
              result.id = newId;
            }
            
            // Save file
            fs.writeFileSync(filePath, JSON.stringify(fileData, null, 2));
            result.count = fileData.length;
          }
          
          console.log(JSON.stringify(result));
          EOF
          
          # Run processor
          node process.js > output.json
          echo "result=$(cat output.json)" >> $GITHUB_OUTPUT

      - name: Commit and push
        if: steps.process.outputs.result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add data/
          if ! git diff --cached --quiet; then
            git commit -m "Update ${{ github.event.client_payload.type }} data"
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          else
            echo "No changes to commit"
          fi
