name: Loan System API
on:
  repository_dispatch:
    types: [loan-api-request]

jobs:
  process-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create API processor
        run: |
          cat > process-request.js << 'EOF'
          const fs = require('fs').promises;
          const path = require('path');

          async function main() {
            try {
              // Read the event payload
              const eventPath = process.env.GITHUB_EVENT_PATH;
              const eventData = JSON.parse(await fs.readFile(eventPath, 'utf8'));
              const payload = eventData.client_payload || {};
              
              const { action, dataType, data, id, operation } = payload;
              
              console.log(`Processing: ${action} for ${dataType}`);
              
              // Ensure data directory exists
              const dataDir = path.join(process.cwd(), 'data');
              try {
                await fs.access(dataDir);
              } catch {
                await fs.mkdir(dataDir, { recursive: true });
              }
              
              let result;
              
              switch(action) {
                case 'GET_DATA':
                  result = await getData(dataType);
                  break;
                  
                case 'SAVE_DATA':
                  result = await saveData(dataType, data, id, operation);
                  break;
                  
                case 'SEARCH_DATA':
                  result = await searchData(dataType, data);
                  break;
                  
                default:
                  result = { success: false, error: 'Unknown action' };
              }
              
              // Output result for GitHub Actions
              console.log('RESULT:', JSON.stringify(result));
              
            } catch (error) {
              console.error('Error:', error.message);
              process.exit(1);
            }
          }

          async function getData(dataType) {
            const filePath = path.join('data', `${dataType}.json`);
            try {
              const content = await fs.readFile(filePath, 'utf8');
              return { success: true, data: JSON.parse(content) };
            } catch (error) {
              // File doesn't exist, return empty array
              if (error.code === 'ENOENT') {
                return { success: true, data: [] };
              }
              throw error;
            }
          }

          async function saveData(dataType, newData, id, operation = 'add') {
            const filePath = path.join('data', `${dataType}.json`);
            
            // Get existing data
            const existing = await getData(dataType);
            let data = existing.data || [];
            
            const timestamp = new Date().toISOString();
            
            if (operation === 'update' && id) {
              // Update existing item
              const index = data.findIndex(item => item.id === id);
              if (index !== -1) {
                data[index] = { ...data[index], ...newData, updatedAt: timestamp };
              } else {
                data.push({ id, ...newData, createdAt: timestamp });
              }
            } else if (operation === 'delete' && id) {
              // Delete item
              data = data.filter(item => item.id !== id);
            } else {
              // Add new item
              const newId = id || `${dataType.toUpperCase().slice(0,3)}-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`;
              data.push({ 
                id: newId, 
                ...newData, 
                createdAt: timestamp,
                createdBy: process.env.GITHUB_ACTOR || 'system'
              });
            }
            
            // Save to file
            await fs.writeFile(filePath, JSON.stringify(data, null, 2), 'utf8');
            
            return { 
              success: true, 
              message: `${operation === 'delete' ? 'Deleted' : 'Saved'} ${dataType}`,
              id: id || newId,
              count: data.length
            };
          }

          async function searchData(dataType, query) {
            const { searchTerm, filters = {} } = query;
            const existing = await getData(dataType);
            let data = existing.data || [];
            
            // Apply filters
            if (filters.status) {
              data = data.filter(item => item.status === filters.status);
            }
            
            if (filters.role) {
              data = data.filter(item => item.role === filters.role);
            }
            
            if (filters.dateFrom) {
              data = data.filter(item => new Date(item.createdAt) >= new Date(filters.dateFrom));
            }
            
            if (filters.dateTo) {
              data = data.filter(item => new Date(item.createdAt) <= new Date(filters.dateTo));
            }
            
            // Apply search term
            if (searchTerm) {
              const term = searchTerm.toLowerCase();
              data = data.filter(item => 
                JSON.stringify(item).toLowerCase().includes(term)
              );
            }
            
            return { success: true, data: data, count: data.length };
          }

          main();
          EOF

      - name: Run API processor
        id: processor
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node process-request.js 2>&1 | tee output.log
          
          # Extract result from logs
          RESULT_LINE=$(grep '^RESULT:' output.log || echo '{"success": false}')
          RESULT_JSON=${RESULT_LINE#RESULT: }
          echo "result=$RESULT_JSON" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.processor.outputs.result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes
          git add data/
          if ! git diff --quiet --staged; then
            git commit -m "Update loan system data via API [skip ci]"
            git push
            echo "Changes committed and pushed"
          else
            echo "No changes to commit"
          fi

      - name: Output result
        run: |
          echo "API processing completed"
          echo "Result: ${{ steps.processor.outputs.result }}"
